### PR TITLE
[WIP] Yet more text/doc updates on PheWAS site

### PR DESCRIPTION
**Pull request by welchr**
Still fiddling. This is likely my last set of changes (or so I think.)

### CODE REVIEW

**Comment by abought** [comment]
It's coming along nicely! Once the endpoint is officially live post-MVP, I might encourage us to add a link to the [portaldev api docs](https://portaldev.sph.umich.edu/docs/api/v1/#overview-of-api-endpoints) for the details of the payload/fields, but retain the list of required fields in this page to help LZjs implementers.

Generally, the goal is to help surface the most official/ maintained version of the docs possible, and help expose people to a broader set of our tools and APIs. (especially when our core data sources so closely mirror our API anyway)

**Comment by welchr** [comment]
The link is there on the page to the API docs. Or did you mean that the payload/fields should be better documented? I had been thinking of adding types expected but it seemed rather obvious from the format of the response, I guess.

**Comment by abought** [comment]
> The link is there on the page to the API docs. Or did you mean that the payload/fields should be better documented? I had been thinking of adding types expected but it seemed rather obvious from the format of the response, I guess.

Durgh. Link is there, which is good. 

If there is heavy overlap between information I tend to lean towards having a single authoritative source rather than two with very similar information (in practice, the downstream copy tends to get out of date). So one option might be to have the sample payload in the API docs, and the specific list of fields needed in LZjs (with their intended meaning for the plot) in this page. 

There's definitely a maintenance vs convenience tradeoff.

**Comment by welchr** [comment]
Part of the reason I was putting some overlapping information on the PheWAS site was mainly because layout and formatting was easier, and we had a little more room for explanation. Sort of like a synopsis vs. the entire official doc. 

The current API docs are rendered by Slate, and they are not too friendly about spacing. I find them hard to read on small screens (probably not so much of a problem for developers who would be using the docs, though.) They also render from Markdown, so you don't have much freedom on formatting. Probably more of an argument for ditching Slate than duplicating docs in two places.

**Pull request merged**
